headers:
  Access-Control-Allow-Origin: "'*'"
  Access-Control-Allow-Headers: "'*'"
  Access-Control-Allow-Credentials: "'true'"
  Content-Type: "'application/json'"
statusCodes:
  400:
    pattern: '.*"statusCode":400,.*' # JSON response
    template: $util.parseJson($input.json('$.errorMessage')) # JSON return object
    headers:
      Content-Type: "'application/json'"
  404:
    pattern: '.*"statusCode":404,.*' # JSON response
    template: $util.parseJson($input.json('$.errorMessage')) # JSON return object
    headers:
      Content-Type: "'application/json'"
  500:
    pattern: '.*"statusCode":500,.*' # JSON response
    template: $util.parseJson($input.json('$.errorMessage')) # JSON return object
    headers:
      Content-Type: "'application/json'"
