handler: src/people/App.handler
memorySize: 128
events:
  - http:
      path: /people
      method: GET
      integration: lambda
      #cors: ${file(config/serverless/http-cors.yml)}
      request:
        template:
          application/json: ${file(config/serverless/request/people/getAllPeople.vm)}
      response: ${file(config/serverless/http-response.yml)}      
  - http:
      path: /people/{id}
      method: GET
      integration: lambda      
      #cors: ${file(config/serverless/http-cors.yml)}
      request:
        template:
          application/json: ${file(config/serverless/request/people/getPeopleById.vm)}
      response: ${file(config/serverless/http-response.yml)}
  - http:
      path: /people/schema
      method: GET
      integration: lambda
      request:
        template:
          application/json: ${file(config/serverless/request/people/getPeopleSchema.vm)}
      response: ${file(config/serverless/http-response.yml)}
