handler: src/planets/App.handler
memorySize: 128
events:
  - http:
      path: /planet
      method: GET
      integration: lambda
      cors: ${file(config/serverless/http-cors.yml)}
      request:
        template:
          application/json: ${file(config/serverless/request/planets/getAllPlanets.vm)}
      response: ${file(config/serverless/http-response.yml)}
  - http:
      path: /planet/{id}
      method: GET
      integration: lambda      
      cors: ${file(config/serverless/http-cors.yml)}
      request:
        template:
          application/json: ${file(config/serverless/request/planets/getPlanetById.vm)}
      response: ${file(config/serverless/http-response.yml)}
  - http:
      path: /search/planet
      method: GET
      integration: lambda
      cors: ${file(config/serverless/http-cors.yml)}
      request:
        template:
          application/json: ${file(config/serverless/request/planets/getPlanetByName.vm)}    
      response: ${file(config/serverless/http-response.yml)}
  - http:
      path: /planet
      method: POST
      integration: lambda
      cors: ${file(config/serverless/http-cors.yml)}
      request:
        template:
          application/json: ${file(config/serverless/request/planets/addPlanet.vm)}
      response: ${file(config/serverless/http-response.yml)}
      private: true